### ISSUE TITLE
FileReadAsync / FileWriteAsync callbacks never getting called

### ISSUE THREAD

**Issue by ddoubledeuce** [rlabrecque/Steamworks.NET#112] opened 2016-08-02 08:53 UTC
Attempting to write or read files using SteamRemoteStorage.FileXXXAsync doesn't seem to be working for me.

I've tried using both a CallResult handler and a Callback handler and neither ever get run.
The SteamAPICall_t that is returned always has a value of 0.
I've verified that  RunCallbacks() is being called every frame.

I have had no problems reading / writing with the blocking FileRead / FileWrite calls.

Are there any known issues with async file operations?

**Comment by FakeLugosi** [comment] 2016-09-19 17:32
Hi, I'm seeing the same issue with with the SteamAPICall_t returned from those two methods being 0 and then never getting the callbacks. 

It doesn't fail 100% of the time, it seems to me that most of the time the first call succeeds and then subsequent ones fail. Did you find a solution to this?

**Comment by ddoubledeuce** [comment] 2016-09-19 17:41
I have not found a solution.

For the time being I am using the blocking calls - since my file writes are very small it doesn't seem to cause any hitching.

**Comment by GiulioPierucci** [comment] 2017-02-17 13:15
that is not a great solution @ddoubledeuce .
the problem is callback object, use callresult instead

           SteamAPICall_t handle = SteamRemoteStorage.FileReadAsync(file, 0, (uint)filesize);
            m_RemoteStorageFileReadAsyncComplete = CallResult<RemoteStorageFileReadAsyncComplete_t>.Create((pCallback, bIOFailure) =>
            {
                if(!bIOFailure && SteamRemoteStorage.FileReadAsyncComplete(pCallback.m_hFileReadAsync, data, (uint)filesize))
                {
                    Debug.Log("Data: " + System.Text.Encoding.ASCII.GetString(data)); 
                }
                if (asyncCallback != null) asyncCallback(data);
            });
            m_RemoteStorageFileReadAsyncComplete.Set(handle);

**Comment by rlabrecque** [comment] 2017-02-21 00:56
Could it be related to this?

https://steamcommunity.com/groups/steamworks/discussions/7/144513248272019400/

That's a genuine problem if it's returning 0 (an invalid handle), but not something that I can fix unfortunately.

**Comment by steinbitglis** [comment] 2017-05-09 08:24
We had the same problem. For us, OnDestroy wasn't getting called consequently, thus the steam api didn't get shut down. The example SteamManager.cs simply was insufficient because of this.
After that, we'd get a handle, and no error message, but we wouldn't get callbacks. This is a nasty bug.
The third time (after a forced shutdown), we would get the null handle and error message. At this point... restarting Steam would somehow place us back on square one, and we would be able to load properly one more time.

**Comment by rlabrecque** [comment] 2017-05-09 19:16
Interesting, did you figure out why OnDestroy wasn't getting called? If you call a Steamworks/SteamManager function during a different OnDestroy elsewhere it will recreate the SteamManager, reinitializing the Steam API.

**Comment by ddoubledeuce** [comment] 2017-05-13 08:18
I have been starting to see hitching during writing files in our application (the save files got a bit bigger), so I went back and re-implemented async file operations using a cached CallResult<> - I create the CallResult<> at startup, and hold on to the reference.

Every time I do a file operation I create a new handle, and set it as the active handle for the CallResult<>.  Async file operations seem to be working for me now.

**Comment by rlabrecque** [comment] 2017-07-12 09:45
Yeah, this is definitely an issue on Valve's side, so I'm going to close this for now, hopefully they fix it soon!

**Closed by rlabrecque** 2017-07-12 09:45 UTC

**Comment by steinbitglis** [comment] 2017-07-12 09:51
I came to believe that the Steam API probably isn't thread safe. We were using a mutex to ensure we weren't using the API simultaneously in different contextst, but then we had to move the code to a thread, so we didn't block the main thread, and prevent RunCallbacks from being called.

**Comment by kolobokspb** [comment] 2024-06-10 00:06
@rlabrecque 

This is a minimal example where FileReadAsync does not work. 
Version 1.57

//true
var init = SteamAPI.Init();

var data = new byte[100];

//ok!, always handleW != 0, callbacks getting called
var handleW = SteamRemoteStorage.FileWriteAsync("aaa.dat", data, (uint)data.Length);

//bad!, always handleR == 0, callbacks never getting called
var handleR = SteamRemoteStorage.FileReadAsync("aaa.dat", 0, (uint)data.Length);
