### ISSUE TITLE
Recursive Leaderboard callbacks do not work.

### ISSUE THREAD

**Issue by WazWaz** [rlabrecque/Steamworks.NET#31] opened 2015-02-03 00:13 UTC
Calling SteamUserStats.DownloadLeaderboardEntries() from within the callresult function of an earlier call does not work (the new call is never callresulted).

This works with C Steamworks (at least, I did it with the Ludosity plugin, so I'd blame the wrapper not Steamworks).

I was using this to incrementally get scores first from around the player, then the top 20, then their friends, and merge them as they arrive. Workaround was to just fire off all 3 calls from the start, which seems to give better results anyway (less lag).

**Comment by rlabrecque** [comment] 2015-02-03 22:19
Hrm yeah, I see, the issue is this line right here:
https://github.com/rlabrecque/Steamworks.NET/blob/master/Plugins/Steamworks.NET/CallbackDispatcher.cs#L275
Moving it above the try..catch block should return normal behavior.

It was moved below in 4cdc16afc01e56d6cb0792807975c2ed1336fc81 solely to be able to access the Handle property from within the CallResults. This in turn made SteamUtils.GetAPICallFailureReason() much more useful as you could use it like:

    private void OnDownloadLeaderboardEntry(LeaderboardScoresDownloaded_t pCallback, bool bIOFailed) {
    		if (bIOFailed) {
    			ESteamAPICallFailure failureReason = SteamUtils.GetAPICallFailureReason(m_LeaderboardScoresDownloaded.Handle);
    			Debug.LogError("OnDownloadLeaderboardEntry bIOFailed = true. Reason: " + failureReason);
    			return;
    		}
    }

A workaround would be to create a new CallResult<> in there.

I'll look into alternatives though and will likely revert that commit.

**Closed** 2015-02-03 22:39 UTC
