### ISSUE TITLE
allow more flexible folder structure

### ISSUE THREAD

**Issue by yamlCase** [rlabrecque/Steamworks.NET#206] opened 2018-01-02 17:12 UTC
It appears Steamworks.NET requires a rigid folder structure as reported in #160 where the asset need to be placed in Assets/Plugins/Steamworks.NET.  Please allow for more flexibility on where to place this.  I personally like to keep all my imported assets in a "modules" folder under Assets to keep the root clean.  Thanks!

**Comment by rlabrecque** [comment] 2018-01-08 05:33
I'm going to close this as a duplicate of #54. It's definitely something I want to do too.

**Closed by rlabrecque** 2018-01-08 05:33 UTC
