### ISSUE TITLE
Crash at shutdown

### ISSUE THREAD

**Issue by ghiboz** [rlabrecque/Steamworks.NET#232] opened 2018-06-02 08:17 UTC
Hi all! my unity code is like this:
```csharp
    // into a script
    void OnDestroy()
    {
        Debug.Log("Main Drive destroyed");
        Steamworks.SteamAPI.Shutdown();
    }
```

and works, but sometimes it crashes unity with this error:
https://www.grally.net/u/uploads/3acc6338addea981f1cdbb1101ffcba9fdf5714b.log

in detail
```
Module 1
E:\Steam games\steamapps\common\gRally\gRallySim_Data\Plugins\steam_api64.dll
Image Base: 0x72230000  Image Size: 0x00041000
File Size:  250656      File Time:  2018-06-01_095352
Version:
   Company:    Valve Corporation
   Product:    Steam Client API
   FileDesc:   Steam Client API
   FileVer:    4.28.51.7
   ProdVer:    1.0.0.1

Module 2
E:\Steam games\steamapps\common\gRally\steam_api64.dll
Image Base: 0x732d0000  Image Size: 0x00041000
File Size:  250656      File Time:  2018-06-01_095352
Version:
   Company:    Valve Corporation
   Product:    Steam Client API
   FileDesc:   Steam Client API
   FileVer:    4.28.51.7
   ProdVer:    1.0.0.1
```

have you got some ideas about this?

My situation is a bit strange: 'cause I have an exe in .NET that is the launcher and it uses also `steam_api64.dll`, this launch my unity game that inside uses `steam_api64.dll` and sometimes crash on close, on shutdown

thanks in advance

**Comment by Igualop** [comment] 2018-06-05 17:08
I also had the "**steam_api64.dll caused an Access Violation**" during shutdown.  But in my case it was caused by some part of my code calling steampi AFTER the shutdown.

I just had to check if it was initialized before making the call

**Comment by jjejj87** [comment] 2018-06-25 01:20
I've found that the crash happens with anything post Unity 2017.4.2 LTS. I have no quit crash in 2017.4.2 LTS but access violation crash with 2017.4.3, 2017.4.4, 2017.4.5 and the latest 2017.4.6

The big issue is that not only does the crash happen at quit, but after 1~2 hours of gaming, the PC standalone crashes randomly as well. All fine in 2017.4.2 LTS though.

Hope this helps!

**Comment by lordvard** [comment] 2018-08-16 09:07
I am having this issue as well on 2017.4.8f1 LTS. Started happening around .4.2 as jjejj87 mentions.
Is there a fix for this issue? It's very annoying for my players.

**Comment by jjejj87** [comment] 2018-08-16 19:48
The issue really hinders development as it forces us to stay on 2017.4.2.

I hope this issue receives the attention it needs.

**Comment by lordvard** [comment] 2018-08-19 17:15
I can confirm that building with 2017.4.2 resolved the issue. Hoping for a fix soon.

**Comment by jjejj87** [comment] 2018-09-04 08:14
I've checked that it works with the latest 2017.4.10 LTS, which tells me that the issue is related to Unity. 

To sum it up, 2017.4.2 and below works and 2017.4.10 works.

**Comment by jjejj87** [comment] 2018-09-10 10:42
spajus, thank you for the info - although I haven't checked that your solution is functional, I still suspect that it was a Unity issue, as 2017.4.2 and 2017.4.10 works fine and anything in between not. Good info regardless.

**Closed** 2018-12-02 23:00 UTC
