### ISSUE TITLE
Crash in RunCallbacks() in Standalone 6.0.0

### ISSUE THREAD

**Issue by AxiomVerge** [rlabrecque/Steamworks.NET#45] opened 2015-04-17 03:06 UTC
Using Steamworks.NET 6.0 standalone Steam API 3.2, I get a System.AccessViolationException after a callback is requested in RunCallbacks().  It happens in native code so there's very little I can tell about this.  

A friend using 3.0.0 and API 2.29 didn't have the error, so I switched that version, where there is no crash.  If there isn't any advantage to using 6.0 I can just use 3.0 for the time being.

Here is what I'm doing:

```c#

//Condensed for brevity/clarity
if (Steamworks.SteamAPI.Init())
{
	mSteamID = new Steamworks.CGameID(Steamworks.SteamUtils.GetAppID());

	m_UserStatsReceived = Steamworks.Callback<Steamworks.UserStatsReceived_t>.Create(OnUserStatsReceived);
	mTrophiesRequested = Steamworks.SteamUserStats.RequestCurrentStats();
}
```

And then, in the main loop,

```c#
	Steamworks.SteamAPI.RunCallbacks();  //Exception.
```

If I do not request current stats, I don't have the crash.

```

**Comment by tomrijnbeek** [comment] 2015-04-17 09:33
Are you using the prebuilt version, because this looks like a duplicate of #41. You should try compiling a binary from source and see if this issue persists.

**Comment by AxiomVerge** [comment] 2015-04-17 15:29
I was, but then downloaded the source zip and built from that, which didn't help.  Does it have the same issue?   If so I can get it directly from git hub...

**Comment by rlabrecque** [comment] 2015-04-24 02:43
Yeah sorry! It's only fixed on github, Valve should be releasing a new version of the SDK soon which will mean a new release and I'll be waiting until then to push this to a release.

**Closed by rlabrecque** 2015-04-24 02:43 UTC

**Comment by AxiomVerge** [comment] 2015-05-14 23:38
I see they're up to 1.33a now ... will there be a binary release soon?
